services:
  - type: web
    name: backend
    env: docker
    plan: free
    dockerfilePath: backend/Dockerfile
    buildCommand: ""
    startCommand: sh -c "python core/manage.py migrate && python core/manage.py runserver 0.0.0.0:8000"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings

  - type: web
    name: frontend
    env: docker
    plan: free
    dockerfilePath: frontend/Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars: []

  - type: redis
    name: redis
    plan: free
