services:
  - type: web
    name: backend
    env: docker
    plan: free
    dockerfilePath: backend/Dockerfile
    buildCommand: ""
    # Remove startCommand! Render will use CMD from Dockerfile
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings

  type: web
  name: frontend
  env: docker
  plan: free
  dockerfilePath: frontend/Dockerfile
  buildCommand: ""
  envVars: []

  - type: redis
    name: redis
    plan: free
    ipAllowList: # Required by Render for Redis
      - source: 0.0.0.0/0
        description: Allow all (for dev/test, restrict for prod)
